[FEATURE] Quickedit the description in timesheet list
kimai/kimai1 pull request #1038
Opened 2017-08-26 15:02 UTC by peterwimmer

FIXES #

Changes proposed in this pull request:
- add a feature to allow inline editing of descriptions in timesheet list

Reason for this pull request:
- this improves our workflow a lot. With this you can change a description directly in the timesheet. We do this a lot.

2017-08-26 15:10 UTC, simonschaufi requested changes
great Feature!

2017-08-26 15:10 UTC, simonschaufi commented on libraries/Kimai/Config/Settings.php
> +
remove empty line

2017-08-26 15:10 UTC, simonschaufi commented on extensions/ki_timesheets/templates/scripts/timeSheet.php
> +                    <input type="text" style="width: 100%" id="description_<?php echo $row['timeEntryID']; ?>" onchange="ts_updateDescription(<?php echo $row['timeEntryID']; ?>, 0)" value="<?php echo
For me, this must be a textarea. What i can imagine is that you first show only one line but when you click on that, the textarea will expand to 3 rows. when you finish editing, the textarea will be one line again. Either we switch it manually or use a jquery plugin here that does that for us. I'm sure there is something like this available ;)

2017-08-26 16:06 UTC, peterwimmer commented on extensions/ki_timesheets/templates/scripts/timeSheet.php
> +                    <input type="text" style="width: 100%" id="description_<?php echo $row['timeEntryID']; ?>" onchange="ts_updateDescription(<?php echo $row['timeEntryID']; ?>, 0)" value="<?php echo
first version is here. in the long run we could really look for something like autogrow. but it works for me now as you proposed :).

2017-08-26 16:43 UTC, simonschaufi commented
one more thing that I request is to show the loading indicator during the ajax request.

2017-08-26 16:44 UTC, simonschaufi requested changes

2017-08-26 16:44 UTC, simonschaufi commented on extensions/ki_timesheets/init.php
> +$view->assign('inlineEditingOfDescriptions', false);
same here with the variable

2017-08-26 16:44 UTC, simonschaufi commented on extensions/ki_timesheets/processor.php
> +            echo json_encode(array('errors'=>$errors));
`echo json_encode(array('errors' => $errors));`

2017-08-26 16:44 UTC, simonschaufi commented on extensions/ki_timesheets/processor.php
> +        Kimai_Logger::logfile("timeEntry_edit: " .$_REQUEST['id']);
space after . missing

2017-08-26 16:44 UTC, simonschaufi commented on extensions/ki_timesheets/processor.php
> +        $database->timeEntry_edit($_REQUEST['id'],$data);
space after comma missing

2017-08-26 16:44 UTC, simonschaufi commented on extensions/ki_timesheets/processor.php
> +        $view->assign('inlineEditingOfDescriptions', false);
use variable here

2017-08-26 17:21 UTC, simonschaufi requested changes

2017-08-26 17:21 UTC, simonschaufi commented on extensions/ki_timesheets/templates/scripts/timeSheet.php
> +                    <textarea rows="1" style="width: 100%" id="description_<?php echo $row['timeEntryID']; ?>" onfocus="$(this).attr('rows',3);" onfocusout="$(this).attr('rows',1);" onchange="ts_upda
add `resize:none` in the styles. Otherwise you can do crazy things with the textarea.... ;)

2017-08-27 14:07 UTC, simonschaufi approved these changes

2017-08-27 14:14 UTC, peterwimmer commented
the ajax loader is still missing, but i don't know at the moment where to look for an example in kimai.... (and i have a rebased version to the now active kimai-develop if this helps?). The rest should be fine :)

2017-08-27 14:16 UTC, simonschaufi commented
yes please (force) push the new rebased version.

I will add the loading in a new commit and then merge it.

2017-08-27 14:31 UTC, peterwimmer commented
should have worked :)

2017-08-27 14:43 UTC, merged