Develop
kimai/kimai1 pull request #1111
Opened 2018-02-09 19:33 UTC by thedayse

FIXES #

Changes proposed in this pull request:

- remove phpjs library
- update jquery ui and add i18n datapicker
- set a global javascript var with the users date format used to format and validate dates in the timesheet entry
- use the duration to set the endtime if the enddate is blank

- 

Reason for this pull request:
Because nobody where I work will use this software if the dates are d.m.Y We need Y-m-d
-

2018-02-09 19:55 UTC, simonschaufi commented
Thank you for your first pull request! Could you please cleanup your code of any commented out code which is not helpful and any console.log?
please also make sure you follow our code style ;) we don't have a javascript checker but it should look nice and clean.

2018-02-09 20:00 UTC, thedayse commented
I am new to git so I have probably done everything wrong. The edits are mostly so that users can enter dates in in their own preferred format. Y-m-d is what I prefer. It turned out to be quite complicated because another dd.mm.yyyy is hardcoded all through the code and what look to be outdated zend date functions and the the phpjs library are used. Jquery ui datepicker can format dates so I updated that with the i18n parts that belong to it and added it to git. I've tested it locally and it seems to work.

2018-02-09 20:04 UTC, thedayse commented
I'll remove all the commented out stuff and console log stuff and submit it again. Not today though. Code style - yes I'll try to get that right as well.

2018-02-09 20:16 UTC, simonschaufi commented
congratulations for making a pull request in the right branch! many others have failed that test already ;) Usually you wouldn't make changes in your own dev branch but create a new branch based on origin/develop because if you want to do another pull request in develop, you first have to clean up your develop branch. So after this thing is done, better delete your local dev branch.

2018-02-10 14:25 UTC, simonschaufi requested changes

2018-02-10 14:25 UTC, simonschaufi commented on installer/processor.php
> +		if (PHP_VERSION_ID < 50400){
why did you change that?

2018-02-10 14:25 UTC, simonschaufi commented on includes/func.php
> +	echo $in, $out;
should be removed

2018-02-10 14:25 UTC, simonschaufi commented on installer/steps/25_system_requirements.php
> +    The following conditions must be met:  <?php //echo PHP_VERSION_ID ?> <br/>
this is not related to any date picker changes

2018-02-10 14:25 UTC, simonschaufi commented on updater/updater.php
> +}
please put that in a new pull request

2018-02-10 14:25 UTC, simonschaufi commented on templates/scripts/core/main.php
> +
remove those empty lines

2018-02-10 14:25 UTC, simonschaufi commented on templates/scripts/core/main.php
> +// this breaks the phpjs/strftime library that is out of date anyway - strftime does not have swedish
why this comment?

2018-02-10 14:29 UTC, thedayse commented on templates/scripts/core/main.php
> +// this breaks the phpjs/strftime library that is out of date anyway - strftime does not have swedish
I was about to remove that..  setting a unsupported locale tag on the html element caused a javascript exception if phpjs was included. So I removed it. I the html is ever to pass wai/wacg then it need to set language/locale

2018-02-10 14:36 UTC, thedayse commented
I think it's ready now..

2018-02-10 14:37 UTC, thedayse commented on installer/steps/25_system_requirements.php
> +    The following conditions must be met:  <?php //echo PHP_VERSION_ID ?> <br/>
It wouldn't install on php7..

2018-02-10 14:39 UTC, thedayse commented on installer/processor.php
> +		if (PHP_VERSION_ID < 50400){
On my ubuntu server with php7 the version test failed. I had to fix it to get it to install..

2018-02-10 14:44 UTC, simonschaufi commented on installer/steps/25_system_requirements.php
> +    The following conditions must be met:  <?php //echo PHP_VERSION_ID ?> <br/>
it will. I have it running on php 7.1

2018-02-10 14:45 UTC, simonschaufi commented on installer/processor.php
> +		if (PHP_VERSION_ID < 50400){
I have Ubuntu 16.04.3 LTS with php 7.1 and it works.

2018-02-10 14:47 UTC, thedayse commented on includes/func.php
> +	echo $in, $out;
ok - I'm wondering if anything calls that function because it has a fixed date format.

2018-02-10 14:49 UTC, simonschaufi commented on installer/processor.php
> +		if (PHP_VERSION_ID < 50400){
the PHP_VERSION constant prints our `7.1.12-3+ubuntu16.04.1+deb.sury.org+1`

2018-02-10 15:39 UTC, thedayse commented on installer/processor.php
> +		if (PHP_VERSION_ID < 50400){
mine prints 
7.1.11-0ubuntu0.17.10.1 
I only remember that I had to change it. The version id is always a number and a better test though.

2018-02-10 15:53 UTC, kevinpapst requested changes

2018-02-10 15:53 UTC, kevinpapst commented on core/processor.php
> +		Kimai_Logger::logfile("timeframe " . $axValue);
Is it possible that you are formatting with tabs? Please switch to spaces for Kimai.
This seems to be the case in almost all places, I am not going to comment on everyone, but only some examples.

2018-02-10 15:53 UTC, kevinpapst commented on extensions/ki_timesheets/js/ts_func.js
> + *
Don't take that personal, but the more unneccessary changes you make, the more complicated the review will be and the more comments you will receive ;-)

2018-02-10 15:53 UTC, kevinpapst commented on updater/updater.php
> +
revert these empty line changes

2018-02-10 15:53 UTC, kevinpapst commented on templates/scripts/core/main.php
> +		var dateFormat = '<?php echo $this->escape($this->kga->getDateFormat(0)) ?>';
tabs vs spaces

2018-02-10 15:53 UTC, kevinpapst commented on templates/scripts/core/main.php
> +	 <!-- conditional locale include - todo use same for timepicker -->
there is a todo left, is that comment still valid?

2018-02-10 15:53 UTC, kevinpapst commented on language/sv.php
> +	'quicklink_today' => 'Idag',
weird formatting

2018-02-10 15:53 UTC, kevinpapst commented on extensions/ki_timesheets/templates/scripts/floaters/add_edit_timeSheetEntry.php
> +				if (startDate.getTime() > endDate.getTime()) {
formatting

2018-02-10 15:53 UTC, kevinpapst commented on extensions/ki_timesheets/processor.php
> +				// could do it this way: $validoutDate->add(new DateInterval("PT".$minutes."M"));
?

2018-02-10 15:53 UTC, kevinpapst commented on extensions/ki_timesheets/processor.php
> +     	Kimai_Logger::logfile("outdate: ".$_REQUEST['end_day'] .' '. $_REQUEST['end_time'].', ' .$kga->getDateFormat(3).' H:i:s');
do we need all these log calls?

2018-02-10 16:58 UTC, thedayse commented on core/processor.php
> +		Kimai_Logger::logfile("timeframe " . $axValue);
yep I'm a tabman. I will try to become a spaceman

2018-02-10 17:02 UTC, thedayse commented on installer/steps/25_system_requirements.php
> +    The following conditions must be met:  <?php //echo PHP_VERSION_ID ?> <br/>
I agree - version compare shouldn't have prevented my install. Something did and the version was red and next wasn't clickable, so I started looking at the version check code. I'll revert this

2018-02-10 17:04 UTC, simonschaufi commented on core/processor.php
> +		Kimai_Logger::logfile("timeframe " . $axValue);
use a proper IDE like phpstorm and tabs will become spaces automatically it setup correctly ;)

2018-02-17 11:32 UTC, thedayse commented
I will break this up into smaller chunks and come back with a new PR presently.. Thanks for your help..

2018-02-17 11:32 UTC, closed without merging