Remote Api Changes
kimai/kimai1 pull request #1202
Opened 2018-06-09 13:38 UTC by xakiru

Hello again,

## Changes proposed in this pull request:
- updateActiveRecording : added "comment" to the proprities that could be updated
- updateActiveRecording : added optional parameter timeEntryID to be able to edit/stop a specific recording 
- startRecord : returns the timeEntryID of the started recording instead of empty array.

## Reason for this pull request:
- I launched KimaiDesktop* interface that use the api to make start/stop recordings one click away.
- The fixes doesn't change the behaviours of the api (no previous application would break)
- These features are basic and would be needed by others anyway.

 * KimaiDesktop: I just finished the first version, I will need to cleanup code before posting it, but the binary is on the repo for testing https://github.com/xakiru/KimaiDesktop

2018-06-09 19:32 UTC, simonschaufi requested changes

2018-06-09 19:32 UTC, simonschaufi commented on libraries/Kimai/Remote/Api.php
> +            $timeSheetEntry=$this->getBackend()->timeSheet_get_data($result[0]);
please trim all whitespace at the end of line

2018-06-09 19:34 UTC, simonschaufi requested changes

2018-06-09 19:34 UTC, simonschaufi commented on libraries/Kimai/Remote/Api.php
> +        $result = array();
use short array syntax

2018-06-09 19:34 UTC, simonschaufi commented on libraries/Kimai/Remote/Api.php
> +            $result[]=$record['timeEntryID'];
add whitespace around `=`

2018-06-09 19:34 UTC, simonschaufi commented on libraries/Kimai/Remote/Api.php
> +            $timeSheetEntry=$this->getBackend()->timeSheet_get_data($result[0]);
add whitespace around `=`

2018-06-09 20:50 UTC, xakiru commented
Thank you @simonschaufi , I made the requested changes.

2018-06-09 20:56 UTC, simonschaufi approved these changes

2018-06-10 10:31 UTC, kevinpapst commented on libraries/Kimai/Remote/Api.php
> +        } else {
Please remove the else, its not required

2018-06-10 10:33 UTC, kevinpapst commented on libraries/Kimai/Remote/Api.php
> +
Extra line is not required ;-)

2018-06-10 10:34 UTC, kevinpapst commented
Hi @xakiru ,
Thanks for your contributions, they are very welcome!
While looking through your PR I wondered why you changed the method `updateActiveRecording` to support passing in an entryId (this method is only meant to update currently a running entry).
Is the method `setTimesheetRecord` probably better fitted for your neeeds? It already supports setting a comment.

2018-06-10 12:53 UTC, xakiru commented
Hello Kevin,
Oh my bad I didn't see those methods, I was assuming that ActiveRecording are the only available methods. I just looked to the code, but it seems that setTimesheetRecord require too many fields for an update feature, don't you think ?

```
  // prepare data array - required values
        $data['userID'] = $user['userID'];
        $data['projectID'] = $record['projectId'];
        $data['activityID'] = $record['taskId'];
        $data['start'] = $in;
        $data['end'] = $out;
        $data['duration'] = $out - $in;
```

Basicly updating would require only 'id' to update.  
- stopping record: would be just by passing 'id' and 'end'
- starting record: would be just by passing 'id' and 'start'
- stop&comment: would be just by passing 'id',  'end' and 'comment'

And so on. Well, there is a way to make things work on my end, either by storing TimesheetRecord data or do an additional request to get TimesheetRecord data just before the updating request so I don't overwrite something edited from kimai panel. But this workaround would be the same for anyone who would use the api.

For the time being I'm going to roll back the change about updateActiveRecording, but the startRecord has to return the timeEntryID anyway otherwise it's really tricky to get the id using another request.

Thank you

2018-06-10 12:59 UTC, simonschaufi commented
This is how the mobile version does it: https://github.com/kimai/kimai-mobile/blob/master/kimai/kimai.mobile.js#L89-L103 It also fetches the active record and then updates it. Is this the way it should be?

2018-06-10 13:12 UTC, xakiru commented
Well on the mobile it's using the stopRecord which doesn't have the possibility of adding a comment, in my case I want to stop the recording and update comment (when provided by user), so here what I'm going to do on stopping:
getTimesheetRecord: get the recent data for a record
setTimesheetRecord: update the fields end, comment (optional)

Thank you for the prompt replies guys 👍

2018-06-10 14:51 UTC, xakiru commented
After switching to use setTimesheetRecord, I had issues on updating records, after debugging I found out that the issue is coming from  the get_best_fitting_rate which return a null value. This should be fixed on my last change.

Thanks,

2018-06-12 10:55 UTC, kevinpapst commented
You could also adjust the method and make all fields optional during update?!
Then you don‘t need the previous fetch, which could potentially lead to race conditions.

This is no REST API in any means, just a basic API utilizing JSON ;-) so I wouldn‘t worry about specifications. And optional fields should not break existing apps (unless they relied on server side validation).

2018-06-12 15:45 UTC, Viras- commented
I strongly recommened to stay with at least a REST like approach - which means fetch the object -> update it -> store it.

2018-06-12 18:03 UTC, xakiru commented
Well, for the time being I will keep using the version where i'm doing fetch before any time_entry update, it's working fine. One more request doesn't really matter after all.
So in this change I will stick to those bug fixes I made, just 2 small file changes:
- startRecord returns timeEntryID ( _instead of **nothing**_ )
- get_best_fitting_rate return 0 if no default rate is found ( _instead of **NULL**_ )
Thanks,

2018-06-12 19:41 UTC, simonschaufi commented
What i would suggest is the following:

Add a white listed array of possible attributes that can be updated in `updateActiveRecording` so that you don't make an if statement for all possible values and then cleanup some dirt there.

Then stopping a recording includes:
- Call `updateActiveRecording` with any comments made
- Call `stopRecord` if you know the currently running id or if you don't, then fetch it again by calling `getActiveRecording`.

2018-06-15 01:15 UTC, xakiru commented
Yea everything is working ok now, all I want is to push is the bug fixes.

2018-06-19 12:37 UTC, xakiru commented
Any news on this ?

2018-06-19 12:41 UTC, simonschaufi commented
I thought you would implement my suggestion but if you don't want, then I can merge it.

2018-06-19 13:51 UTC, xakiru commented
Yea since the api works as it is, no need to make changes I guess. The current made change is just a bug fixe.

2018-06-19 14:09 UTC, merged

2018-06-24 14:33 UTC, simonschaufi commented
@Viras- I didn't find your email address in the commit log so there is no other way to contact you than here. Could you get in touch with me via email: my github username [at] gmail [dot] com

2018-11-30 12:54 UTC, Viras- commented
Hi @simonschaufi I'm sorry I just saw your post and I just sent you an e-mail.