Fix password reset link when KIMAI runs on a custom port
kimai/kimai1 pull request #1214
Opened 2018-06-25 07:20 UTC by mawa85

Added port number to Password reset mail.

FIXES #

Changes proposed in this pull request:
- add Port number to Password reset link

Reason for this pull request:
- I'm running KIMAI on another port. Password reset generates a link without the port so the link won't work

2018-06-25 07:23 UTC, kevinpapst requested changes

2018-06-25 07:23 UTC, kevinpapst commented on libraries/Kimai/Auth/Kimai.php
> +        $url = ($ssl ? 'https://' : 'http://') . $_SERVER['SERVER_NAME'] . ':' . $_SERVER[SERVER_PORT] . dirname($_SERVER['SCRIPT_NAME']) . '/forgotPassword.php?name=' . urlencode($name) . '&key=' .
can you calculate the port before and only append it in case its not the default port 80/443?

2018-06-25 07:23 UTC, kevinpapst commented
Thanks @mawa85 for the contribution!

2019-09-28 22:32 UTC, simonschaufi commented
no response. closing

2019-09-28 22:32 UTC, closed without merging