A few correction to fr translation file and adding *.iml file to gitignore
kimai/kimai1 pull request #1220
Opened 2018-07-02 12:55 UTC by crockstylie

FIXES #

Changes proposed in this pull request: Some fr translation improvements (respect fr typography adding a space before composed periods (:!?)
Adding the *.iml file to gitignore for intellij users (that file is specific to the project name and should not be sent to repo
- 

Reason for this pull request: Because it is my pleasure to help ;) plus, it is my very first pull request of all my life ;)
-

2018-07-02 13:29 UTC, kevinpapst commented
So the space before the composed periods is an "official rule" for French?

2018-07-02 18:29 UTC, simonschaufi requested changes

2018-07-02 18:29 UTC, simonschaufi commented on .gitignore
> +*.iml
Since `.idea` is already excluded, this is really not neccesary

2018-07-02 18:30 UTC, simonschaufi commented
I studied frensh and never heard about this space thing

2018-07-02 21:32 UTC, crockstylie commented on .gitignore
> +*.iml
Excluding .idea folder doesn't exclude my_project_name.iml chich is at the same root level that the folder

2018-07-02 22:26 UTC, simonschaufi commented on .gitignore
> +*.iml
how comes that the iml file is at the root folder? It shouldn't be there. Just delete it. Jetbrains products store all meta files in the .idea foder.

2018-07-02 22:27 UTC, simonschaufi commented
I will only merge this if you can proove that the space thing is something official.

2018-07-03 07:56 UTC, crockstylie commented on .gitignore
> +*.iml
![image](https://user-images.githubusercontent.com/6499262/42206195-b4e28376-7ea6-11e8-8180-8f4d8ab7fac6.png)
Well, maybe I'm doing something wrong since always, but every time I create a new project, It creates a .iml file in the project root folder with the name of my project. Am I the only one ? I must confess, I never had the curiosity of searching what is its purpose. 
See that StackOverFlow thread : https://stackoverflow.com/questions/36542288/intellij-ide-iml-file-lost-or-deleted

2018-07-03 08:00 UTC, crockstylie commented on .gitignore
> +*.iml
For the spacxe thing, as I am French, and I am known to be a very good grammar guy, it's something I have always known. Now, have a look at these posts : http://grammaire.reverso.net/5_1_10_les_espaces_et_la_ponctuation.shtml
http://www.kalligo.com/fiche-pratique/rediger/lettre/336-regles-ponctuations-mettre-espaces.htm
http://monsu.desiderio.free.fr/atelier/espace.html
https://www.biblio.univ-evry.fr/assets/files/formations/autoformation/guide-typographie-miseenpage_BUEvry.pdf
http://www.sophieviguiercorrectrice.com/pages/mes-orthotrucs/les-ortho-trucs-precedents/ponctuation/ponctuation-et-espaces.html
http://vdl19.pagesperso-orange.fr/Pages_Astuces/regles_ponctuation.htm
http://typographisme.net/post/Les-espaces-typographiques-et-le-web
Will that be enough ? ;)

2018-07-03 08:57 UTC, kevinpapst commented on .gitignore
> +*.iml
The .iml fine is totally fine to be merged. For the french translation someone else needs to have a look. I am just curious, as I am working on several OS projects and can't remember to have seen that by now. But I don't speak french, so I cant judge.

2018-07-03 12:48 UTC, crockstylie commented on .gitignore
> +*.iml
Hi :) thanks for the .iml file. If you want, I found other posts, in english this time about French punctuation marks : 
https://www.duolingo.com/comment/7344/Spaces-before-punctuation-marks
https://www.thoughtco.com/how-to-use-french-punctuation-4086509
https://www.fluentu.com/blog/french/french-punctuation/
https://www.iwillteachyoualanguage.com/learn/french/french-tips/french-punctuation

Well, you need a space before and after complex punctuation marks including :-!-?-;-"
That's it. I personnaly appologize for that strangity ;)

2018-07-04 17:55 UTC, kevinpapst commented on .gitignore
> +*.iml
Wow, thanks to the Duolingo link I finally know what that strange whitespace is, that I sometimes have in my source code. Seems I hit Option+Space on my Mac and create an error with that special french space where you can't see the difference between the normal and special space.
Which version did you use during the translation? The non-breaking one?

2018-07-04 17:56 UTC, kevinpapst commented
@simonschaufi as I do not speak a word French, you have to take over.

2018-07-05 07:22 UTC, crockstylie commented on .gitignore
> +*.iml
;) You are welcome
And yes, I used the non-breaking one.

2019-11-19 21:08 UTC, simonschaufi approved these changes

2019-11-19 21:09 UTC, merged