WIP: Turkish language support (first 100 Line)
kimai/kimai1 pull request #1300
Opened 2019-09-18 11:59 UTC by guneysus

Reason for this pull request:
- Turkish language support is being added

2019-09-22 22:35 UTC, simonschaufi commented
Thank you. I will merge it, if translation is complete

2019-09-23 15:53 UTC, simonschaufi requested changes

2019-09-23 15:53 UTC, simonschaufi commented on language/tr.php
> +    "hours" => "hours",
missing

2019-09-23 15:53 UTC, simonschaufi commented on language/tr.php
> +    "in" => "In",
missing

2019-09-23 15:53 UTC, simonschaufi commented on language/tr.php
> +    "admin" => "Admin",
missing

2019-09-23 15:53 UTC, simonschaufi commented on language/tr.php
> +    "breiteZeitspalte" => "width time column",
missing

2019-09-23 15:53 UTC, simonschaufi commented on language/tr.php
> +    "day_summary" => "Time summary",
missing

2019-09-23 15:53 UTC, simonschaufi commented on language/tr.php
> +    "recordAgain" => "Record this recording again",
missing

2019-09-23 15:53 UTC, simonschaufi commented on language/tr.php
> +    'all_activities' => '&lt;&lt;all&gt;&gt;',
this doesn't look correct

2019-09-24 05:31 UTC, guneysus commented on language/tr.php
> +    'all_activities' => '&lt;&lt;all&gt;&gt;',
I translated `view_filter` to meaning `show the filter`. Does not it correct?.
And Changed `unassigned` to meaning `Things that are not assigned`. 
`decimal_seperator` and `all_activities` should be correct.

2019-09-28 22:18 UTC, simonschaufi commented on language/tr.php
> +    'all_activities' => '&lt;&lt;all&gt;&gt;',
looks good now.

2019-09-28 22:19 UTC, simonschaufi approved these changes

2019-09-28 22:27 UTC, merged