Adding optional 'description' parameter on startRecord and stopRecord API
kimai/kimai1 pull request #829
Opened 2016-09-07 16:47 UTC by christmasso

Changes proposed in this pull request:
- adding an optional parameters on startRecord and stopRecord API. The parameter contains the description of the related activity.

Reason for this pull request:
- a mobile version of kimai with the possibility to add the description can be useful (see also the feature request 'Add description field' on kimai-mobile).
- in the following days I will release a new native kimai Android app with GPL license that will use the modified API. Now the Android app is in beta-testing.

2016-09-07 18:51 UTC, kevinpapst commented
Hey, I really like the idea for a native GPL app. Fantastic News!!!
If you need beta tester, I am here to help :-)

Regarding your PR: the changes might be logical from a UI/UX perspective, but from an API perspective they are not the way I would design them.
Please try to implement it with separate calls. One to start/stop and one for an

2016-09-07 18:52 UTC, kevinpapst commented
Ups, github mobile view is complicated ;-)

2016-09-07 21:46 UTC, christmasso commented
Perfect, I'm happy to add you as beta tester! :-)

To clarify the problem related to the API design: do you think it is more appropriate to have various calls for the single parameters (like setDescription, setLocation, etc...) or have an optional $data object passed to the start/stop calls managing all the allowed parameters?

2016-09-07 21:55 UTC, simonschaufi commented
I would also like to have access to the native app!
I think 2 calls is not the best idea. I would vote for the second option with the optional data array.

2016-09-08 12:27 UTC, kevinpapst commented
I would say: leave the stop function as It is. The optional data array
could be placed in the start function and should support as many fields as
possible.

From an API perspective there should be a function to update an entry,
which could be called internally by the start function.

What do you need from us to get a beta apk?

Am 07.09.2016 23:55 schrieb "Simon Schaufelberger" <notifications@github.com
>:

> I would also like to have access to the native app!
> I think 2 calls is not the best idea. I would vote for the second option
> with the optional data array.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/kimai/kimai/pull/829#issuecomment-245432127>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAgiqhsWuJnIH7zBWXIZCtVkn4yI0_cjks5qnzLvgaJpZM4J3IZI>
> .
>

2016-09-08 16:59 UTC, christmasso commented
Sounds good, I'll proceed with your advices.

I'll need your android/gmail account to add you as a test members, so that you can see the beta version of the app from the google play store.

2016-09-12 10:39 UTC, christmasso commented
I have added an update entry function API, that will also be called by the start recording if optional data are passed.
It uses the already written timeEntry_edit (in Mysql.php) to update data on DB, since the logic needed is the same.

@kevinpapst I'm writing to your personal mail for details about the beta testing. Please share it with Simon, I didn't immediately find his email address :-)

2018-02-28 14:08 UTC, simonschaufi requested changes

2018-02-28 14:08 UTC, simonschaufi commented on libraries/Kimai/Remote/Api.php
> +        $entryId = $this->getBackend()->startRecorder($projectId, $activityId, $uid);
instead of creating  new record here and update it a few lines later, I would suggest passing the data here already and process it right in the startRecorder method. @kevinpapst what do you think?

2018-02-28 14:08 UTC, simonschaufi commented on libraries/Kimai/Remote/Api.php
> +     * @param integer $entryId
please use `int`

2018-02-28 14:08 UTC, simonschaufi commented on libraries/Kimai/Remote/Api.php
> +            if (array_key_exists('timeEntryID', $result)) {
`if (isset($result['timeEntryID']))`

2018-02-28 14:08 UTC, simonschaufi commented on libraries/Kimai/Database/Mysql.php
> -
please leave it like it was.

2018-02-28 17:04 UTC, kevinpapst requested changes

2018-02-28 17:04 UTC, kevinpapst commented on libraries/Kimai/Remote/Api.php
> +    public function startRecord($apiKey, $projectId, $activityId, $data = null)
an array should be initialized with `$data = array()` instead of `$data = null` ...

2018-02-28 17:04 UTC, kevinpapst commented on libraries/Kimai/Remote/Api.php
> +            if (!is_null($data)) {
... and here a check for `if (!empty($data))`

2018-02-28 17:04 UTC, kevinpapst commented on libraries/Kimai/Remote/Api.php
> +        if ($entryId == '') {
Return early:
```
if (empty($entryId)) {
    return $this->getErrorResult('Invalid entry ID given');
}
```

2018-02-28 17:04 UTC, kevinpapst commented on libraries/Kimai/Remote/Api.php
> +    public function updateEntry($apiKey, $entryId, $record)
Please rename `$record` to `$data` as it is misleading - I first thought this is a database record

2018-02-28 17:04 UTC, kevinpapst commented on libraries/Kimai/Remote/Api.php
> +            $data['location'] = $record['location'];
`$data` should then be renamed to `$updateValues` and please initialize it before using: 
`$updateValues = array();`

2018-02-28 17:04 UTC, kevinpapst commented on libraries/Kimai/Remote/Api.php
> +                $this->updateEntry($apiKey, $entryId, $data);
You need to check the result from that call. If you passed in data the update of the new entry failed, then the API consumer should be notified about it.

2018-02-28 17:06 UTC, kevinpapst commented
Thanks for your contribution @christmasso 👍 - I added some comments, please have a look.

2018-02-28 17:09 UTC, kevinpapst commented
Oha, just saw how old this PR is... we must have missed it.
@christmasso do you still want to work on it or should it be closed?

2018-11-04 14:12 UTC, simonschaufi commented
@christmasso any update?

2019-11-19 21:23 UTC, simonschaufi commented
No response and won't fix.

2019-11-19 21:23 UTC, closed without merging