Pdf export added fields 861
kimai/kimai1 pull request #997
Opened 2017-06-16 16:07 UTC by ptalus

FIXES #

Changes proposed in this pull request:
- added code to show 'description' field in exported PDF   
- added code to show 'time out' field in exported PDF   

Reason for this pull request:
-  Exported PDF does not show content of description and end/out time #861

2017-06-22 19:50 UTC, simonschaufi requested changes
Please use PSR-2 coding standards meaning after an if there must be curly brackets.

2017-06-23 11:00 UTC, ptalus commented
I made the fixes to fit PSR2 in export_pdf.php
Regrading the export_pdf2.php, I tried to fit styling convention which i see in the file, but it does not looks like PSR2. I can run code beautifier to change it to PSR2 but I doubt then it will be hard to review actual changes I made.

2018-01-12 23:40 UTC, simonschaufi approved these changes

2018-01-12 23:43 UTC, simonschaufi commented
I manually merged your pull request in develop branch.

2018-01-12 23:43 UTC, closed without merging